name: Stock Monitor

on:
  schedule:
    - cron: "*/5 3-9 * * 1-5" # Every 5 minutes, Monday-Friday, 9 AM - 4 PM
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Decode Firebase credentials
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDENTIALS" | base64 --decode > stock-monitoring-fb.json
      - name: Verify Firebase JSON File Content
        run: cat stock-monitoring-fb.json
      - name: Run the script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
          DHAN_API_KEY: ${{ secrets.DHAN_API_KEY }}
          DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: stock-monitoring-fb.json
        run: python script.py
