name: Stock Monitor

on:
  schedule:
    - cron: "*/5 9-16 * * 1-5" # Every 5 minutes, Monday-Friday, 9 AM - 4 PM

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python script.py
